# -*- coding: utf-8 -*-
"""Rock Paper Scissor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bmPrqSPa4B93ZuWh5XV2qiFkn_L2k45R
"""

import random
print("                                          ****************Welcome to the Rock Paper Scissor Game****************")

print("---------\nRules of the game:\n 1. Rock v/s Paper: Paper wins\n 2. Rock v/s Scissor: Scissor wins\n 3. Scissor v/s Paper: Paper wins\n---------\n\n" )

print("Enter a choice number:\n 1. Rock\n 2. Scissor \n 3. Paper\n")
choice= int(input("User choice is: "))
while choice<1 or choice>3:
  choice= int(input("Enter a valid input: "))


if(choice==1):
  user_choice='Rock'
if(choice==2):
  user_choice='Scissor'
if(choice==3):
  user_choice='Paper'
print("The selected choice is: ",user_choice)
print("\n")

print("Now is computer's turn!")

comp_choice = random.randint(1,3)

while choice==comp_choice:
  comp_choice = random.randint(1,3)

if(comp_choice==1):
  comp_choice_name= 'Rock'
elif comp_choice==2:
  comp_choice_name='Scissor'
else: 
  comp_choice_name='Paper'

print("The computer's choice is: ",comp_choice_name)
print(user_choice +" v/s " +comp_choice_name)

if((choice==1 and comp_choice==3) or (choice==3 and comp_choice==1)):
  print("Paper Wins!\n")
  result="Paper"

if((choice==2 and comp_choice==3) or (choice==3 and comp_choice==2)):
  print("Scissor Wins!\n")
  result="Scissor"

if((choice==1 and comp_choice==2) or (choice==2 and comp_choice==1)):
  print("Rock Wins!\n")
  result="Rock"

if(user_choice==result):
  print("**************************************  Y o u    W i n!!!!  **************************************")
else:
  print("**************************************  C o m p u t e r   W i n s!!!  **************************************")

print("Thanks for playing!")